### ISSUE TITLE
Gradle for Quantum

### ISSUE THREAD

**Issue by Spartan322** [QuantumTheoryMC/QuantumAPI#3] opened 2015-12-22 18:02 UTC
Quantum would be more effective and easier to implement using [gradle](http://gradle.org) (there are only positives for gradle as far as I can tell).

I could try a rudimentary gradle implementation if you'd like, but I haven't used it much before.

**Comment by Caritas-Dei** [comment] 2015-12-22 18:09
Feel free to make a gradle implementation. I've always wanted to use gradle but never got to doing it or understanding how to.

**Comment by gizmocodes** [comment] 2015-12-22 18:26
Easy; just steal the gradle files from [Forge](https://github.com/MinecraftForge/ForgeGradle) and modify them to work with the Quantum Project.

**Comment by Caritas-Dei** [comment] 2015-12-22 18:37
As if I would be that low key lol. I would make it from scratch. And I will.

**Comment by gizmocodes** [comment] 2015-12-22 18:43
Suit yourself, just saying!

**Comment by Caritas-Dei** [comment] 2015-12-22 18:45
I totally get what your saying Eric, but just using forge gradle would require a lot of unnecessary refactoring because it is largely unrelated

**Comment by Spartan322** [comment] 2015-12-24 18:04
that depends on how we plan to handle patching, we might be able to just yank the Forge patching system. Or we could study the Forge patching system, I would much prefer study and reproduce if we do patching (because that is seriously the only thing worth looking at in this project)

**Comment by Caritas-Dei** [comment] 2015-12-24 18:45
Screw studying is what I prefer. I plan on building from scratch and doing
it right the first time! Besides, I want to learn gradle. We could just
study and reproduce, but I honestly think it would be faster and easier to
go from scratch on this one.

**Comment by Caritas-Dei** [comment] 2015-12-24 19:51
Also I took a glance at forge gradle. It is quite different than how I plan to use it to build Quantum API and how I would implement tasks for gradle.

**Comment by ezra-en** [comment] 2016-01-23 12:54
I'd be fine with lots of unneccesary refactoring.

**Comment by ezra-en** [comment] 2016-01-23 12:56
Just using Gradle's build files could be feasible, but not as flexible as writing our own wrapper.

**Comment by ezra-en** [comment] 2016-01-23 12:59
Right, scrap the wrapper, we're writing a gradle plugin instead.
I used some really bad wording earlier.

**Comment by Caritas-Dei** [comment] 2016-06-23 16:50
Closing this. Quantum API will not be built using Gradle, as far as I'm concerned. (I'll remove gradle related things soon enough from the repo)

**Closed as completed by Caritas-Dei** 2016-06-23 16:50 UTC
Labels: enhancement
